name: Xabula
favicon: null
layout_spectrum: 0.5723470062948763
typography_spectrum: 0.43522145436145365
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7735128789208829
  lightness: 0.2600777926854789
  saturation: 0.48941831244155765
  rhythmicContrast: 0.06876493105664849
purpose: []
